# Use postgres/example user/password credentials
services:
  db:
    image: postgres:16-bullseye
    # restart: always
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: ${DB_CONTAINERNAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  bucket:
    image: minio/minio
    # restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ${S3_USERNAME}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
    container_name: mbucket
    volumes:
      - ./minio:/data
    command: server --console-address ":9001" /data
